import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import React from "react";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
  authors : [{
    name : "Ibrahim Khan",
    url : "/",
  }]
};

const links = [
  {
    name : "Home",
    where : "/",
  },
  {
    name : "Blog",
    where : "/blog",
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className='w-full flex flex-col justify-center items-center'>
            <Navbar links={links} />
              {children}
          </main>
        </ThemeProvider>  
      </body>
    </html>
  );
}
